name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: Karthik-Nayak98/Greeting-action@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        issue_message: 'Hello @${{github.actor}}, <br>
                        Thanks for opening a new issue to this repo! :partying_face: <br>
                        Don't forget to go through our Code of Conduct and Contributing Guidelines, and wait until you get assigned by one of our maintainers to work on the issue!

        PR_message:
                      '<h1> :partying_face: Congratulations :tada: </h1>:pray:
                      Thank you @${{github.actor}} for taking out your time and contributing to our project. Our team will now review this and if everything looks good it will be merged.'
